// <auto-generated />
namespace WebApplication2._13.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Bla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bla));
        
        string IMigrationMetadata.Id
        {
            get { return "201702122148067_Bla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
